create table if not exists decision_context_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  human_decision_journal_entry_id bigint,
  ticker text not null,
  latest_run_id text not null,
  business_date_hkt date,
  decision_type text,
  confidence_label text,
  snapshot_schema_version integer,
  created_at_hkt text,
  delay_minutes integer,
  data_as_of_type text,
  snapshot_json jsonb not null,
  reference_price double precision,
  previous_close double precision,
  change double precision,
  change_pct double precision,
  volume double precision,
  turnover double precision,
  currency text,
  market text,
  data_source text,
  data_timestamp_hkt text,
  freshness_status text,
  freshness_label text,
  market_data_acceptance_status text,
  market_data_acceptance_warning text,
  limitations jsonb,
  paper_trade_only boolean not null default true,
  decision_support_only boolean not null default true,
  no_broker_execution boolean not null default true,
  no_real_money_execution boolean not null default true
);
alter table decision_context_snapshots enable row level security;
create index if not exists idx_decision_context_snapshots_journal_entry_id on decision_context_snapshots (human_decision_journal_entry_id);
create index if not exists idx_decision_context_snapshots_ticker_business_date on decision_context_snapshots (ticker, business_date_hkt);
create index if not exists idx_decision_context_snapshots_latest_run_id on decision_context_snapshots (latest_run_id);
