-- Milestone 2: basic run-level observability for scheduled jobs.
-- Run once in Supabase SQL editor or migration pipeline.
CREATE TABLE IF NOT EXISTS public.runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    processed_tickers INTEGER,
    successful_tickers INTEGER,
    failed_tickers INTEGER,
    error_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_runs_started_at ON public.runs (started_at DESC);
