from __future__ import annotations

from typing import Any


def build_railway_cadence_activation_plan() -> list[dict[str, Any]]:
    required_env = ["AIHK_RUN_TYPE"]
    return [
        {
            "service_key": "paper-daily-runner",
            "run_type": "post_close_daily_review",
            "intended_hkt_window": "20:00 HKT",
            "railway_cron_utc": "0 12 * * *",
            "activation_state": "existing_baseline_to_verify",
            "purpose": "post-close formal paper review",
            "required_env": required_env,
            "acceptance_evidence_required": True,
            "paper_only": True,
            "creates_orders": False,
            "broker_connection": False,
            "manual_operator_step_required": True,
            "notes": "Baseline exists in repo contract but still requires staged Railway verification evidence.",
        },
        {
            "service_key": "paper-midday-monitor",
            "run_type": "midday_market_monitor",
            "intended_hkt_window": "around 12:30 HKT weekday",
            "railway_cron_utc": "30 4 * * 1-5",
            "activation_state": "candidate_requires_manual_railway_setup",
            "purpose": "automatic midday data/freshness/risk check",
            "required_env": required_env,
            "acceptance_evidence_required": True,
            "paper_only": True,
            "creates_orders": False,
            "broker_connection": False,
            "manual_operator_step_required": True,
            "notes": "Railway cron uses UTC and is best-effort timing (non minute-precise).",
        },
        {
            "service_key": "paper-stale-risk-refresh",
            "run_type": "stale_risk_refresh",
            "intended_hkt_window": "weekday diagnostic window around 15:30 HKT",
            "railway_cron_utc": "30 7 * * 1-5",
            "activation_state": "candidate_requires_manual_railway_setup",
            "purpose": "refresh candidate when freshness/risk context is insufficient",
            "required_env": required_env,
            "acceptance_evidence_required": True,
            "paper_only": True,
            "creates_orders": False,
            "broker_connection": False,
            "manual_operator_step_required": True,
            "notes": "Low-frequency diagnostic cadence only; not real-time monitoring.",
        },
        {
            "service_key": "planned-pre-market-readiness",
            "run_type": "pre_market_readiness_check",
            "intended_hkt_window": "around 08:45 HKT weekday",
            "railway_cron_utc": "45 0 * * 1-5",
            "activation_state": "planned_later",
            "purpose": "future pre-market readiness check",
            "required_env": required_env,
            "acceptance_evidence_required": True,
            "paper_only": True,
            "creates_orders": False,
            "broker_connection": False,
            "manual_operator_step_required": True,
            "notes": "Planned after midday/stale-risk activation acceptance sequence.",
        },
        {
            "service_key": "planned-event-context-refresh",
            "run_type": "event_context_refresh",
            "intended_hkt_window": "event-driven, not scheduled now",
            "railway_cron_utc": "TBD",
            "activation_state": "planned_later",
            "purpose": "future announcement/news/event context refresh",
            "required_env": required_env,
            "acceptance_evidence_required": True,
            "paper_only": True,
            "creates_orders": False,
            "broker_connection": False,
            "manual_operator_step_required": True,
            "notes": "Requires later provider/event trigger design; not activated in Step 136C.",
        },
    ]
